### ISSUE TITLE
Problemas al registrar pagos completo en facturas de proveedores Mx Sh v.17

### ISSUE THREAD

**Issue by NicolasOT** [Vauxoo/osmexico#8]
Saludos @luistorresm 

En cliente presenta el siguiente error al momento de registrar un pago por el 100% del monto en una factura de proveedor

![image](https://github.com/Vauxoo/osmexico/assets/112537218/1f20883e-a312-4151-ba33-e35c4fe57cab)

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/account/wizard/account_payment_register.py", line 958, in action_create_payments
    payments = self._create_payments()
  File "/home/odoo/src/enterprise/hr_payroll_account/wizard/account_payment_register.py", line 11, in _create_payments
    payments = super()._create_payments()
  File "/home/odoo/src/odoo/addons/account/wizard/account_payment_register.py", line 954, in _create_payments
    self._reconcile_payments(to_process, edit_mode=edit_mode)
  File "/home/odoo/src/enterprise/hr_payroll_account/wizard/account_payment_register.py", line 24, in _reconcile_payments
    res = super()._reconcile_payments(to_process, edit_mode=edit_mode)
  File "/home/odoo/src/odoo/addons/account/wizard/account_payment_register.py", line 894, in _reconcile_payments
    .reconcile()
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 2945, in reconcile
    return self._reconcile_plan([self])
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 2355, in _reconcile_plan
    self._reconcile_plan_with_sync(plan_list, all_amls)
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 2513, in _reconcile_plan_with_sync
    caba_lines_to_reconcile = involved_amls._add_exchange_difference_cash_basis_vals(exchange_diff_values)
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 2773, in _add_exchange_difference_cash_basis_vals
    move_vals['date'] = max(move_vals['date'], move.date)
TypeError: '>' not supported between instances of 'datetime.date' and 'bool'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://vauxoo-osmexico-17-0-osmexico-migration-desdelinux-12320346.dev.odoo.com/web/assets/53f30e0/web.assets_web.min.js:2879:163)
    at XMLHttpRequest.<anonymous> (https://vauxoo-osmexico-17-0-osmexico-migration-desdelinux-12320346.dev.odoo.com/web/assets/53f30e0/web.assets_web.min.js:2883:13)

Pasos para replicar el error:
1. Generar un factura de proveedor
2. En la linea de la factura agregar el IVA de compra "IVA DE COMPRAS (servicios)"
3. Confirmar la factura
4. Registrar el pago por el 100%
5. Forma de pago "Transferencia electrónica de fondos"
6. "Crear Pago" 

URL TAREA: https://www.vauxoo.com/web#cids=1&menu_id=1490&action=1928&model=project.task&view_type=form&id=81018

**Comment by luistorresm** [comment]
Hola @NicolasOT 

Este error no es parte de localizaciones.

@desdelinux no se si te suene a algo de la migración? o le pedimos a Hugo que nos ayude a revisar?

Saludos

**Comment by desdelinux** [comment]
Hola @NicolasOT asigname a mi, yo veo todo lo de migración. Ya después de escala al área correcta. Por favor

**Comment by desdelinux** [comment]
Hola @CLaurelB encargate de esto, por favor.

**Comment by CLaurelB** [comment]
Hola @desdelinux, ese error sale porque el campo currency_exchange_journal_id ("Currency Exchange Journal") de la compañía no tiene un diario asociado. Por el momento, según lo que he revisado, ese campo se configura en "Settings" > "Post Exchange difference entries in:" > "Journal" y solo se puede visualizar esa configuración si el usuario pertenece a los grupos "Mostrar características de contabilidad completas" y "Multidivisa".

Las compañias que no tienen un diario asociados en el campo que menciono son los que tienen los siguientes IDs:  4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15

**Comment by CLaurelB** [comment]
Hola @desdelinux adicionalmente lo que faltaría para que se pueda ver la configuración en "Settings" es agregar una divisa adicional en "Contabilidad" > "Configuración" > "Divisas".
